services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    volumes:
      - .:/workspace
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
    # devcontainer用: コンテナを起動したままにする
    command: tail -f /dev/null
