services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "true"
    volumes:
      - .:/workspace
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/workspace
      - DATABASE_URL_USERS=mysql+pymysql://user:password@db:3306/users_db
      - DATABASE_URL_FOOD_CATEGORIES=mysql+pymysql://user:password@db:3306/food_categories_db
      - DATABASE_URL_FOODS=mysql+pymysql://user:password@db:3306/foods_db
      - DATABASE_URL_USER_FOODS=mysql+pymysql://user:password@db:3306/user_foods_db
      - DATABASE_URL_RECIPES=mysql+pymysql://user:password@db:3306/recipes_db
      - DATABASE_URL_RECIPE_FOODS=mysql+pymysql://user:password@db:3306/recipe_foods_db
      - DATABASE_URL_RECEIPTS=mysql+pymysql://user:password@db:3306/receipts_db
      - DATABASE_URL_RAW_FOOD_MAPPINGS=mysql+pymysql://user:password@db:3306/raw_food_mappings_db
      - DATABASE_URL_RECEIPT_DETAILS=mysql+pymysql://user:password@db:3306/receipt_details_db
    command: tail -f /dev/null
    depends_on:
      - db
    networks:
      - default

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_dev_data:


networks:
  default:
    name: receipt-recipe-dev
